### ISSUE TITLE
95 % credible intervals

### ISSUE THREAD

**Issue by a-qvecell** [xavierdidelot/DetectImports#3]
Hi :)
Thank you for a nice package, very neatly implemented in R!
I was just wondering; when I run the examples from you demo vignette, I find that most of the coalescence intervals fall outside of the dashed blue lines.
I am probably just interpreting it in a wrong way, but I would have expected 95% of them to fall within this interval.
Can you explain why this is not the case?
Best regards,
Amanda

**Comment by xavierdidelot** [comment]
Hi Amanda,

Thanks for opening this issue!

I have just pushed the documentation of DetectImports, you can access it at https://xavierdidelot.github.io/DetectImports
In particular you can see what the output of the demonstration.Rmd vignette should look like at https://xavierdidelot.github.io/DetectImports/articles/demonstration.html
Hopefully the output looks the same on your side.

You are correct that most of the coalescent intervals do not fall within the dotted blue lines. This is because these lines represent the 95% interval for the parameter that corresponds to the **mean** of the coalescent intervals, not the 95% interval of the coalescent intervals themselves. 

I hope this makes sense, don't hesitate to reopen this issue if not.

Best wishes,
Xavier

**Comment by a-qvecell** [comment]
Hi Xavier,
that makes perfect sense, thank you for the explanation. My output looks the same, so I believe it is all good.
Thank you for the speedy reply, just in time for my journal club presentation of your paper :)
Have a nice day,
Best wishes,
Amanda
